-- Get owner IDs and insert cars
WITH owner_ids AS (
  SELECT id FROM users WHERE role = 'owner' ORDER BY created_at LIMIT 2
)
INSERT INTO vehicles (id, owner_id, make, model, variant, year, color, seating, fuel_type, transmission, mileage_kmpl, city, state, address, price_per_hour, price_per_day, security_deposit, registration_number, status, kyc_status, features, created_at, updated_at)
VALUES
  (gen_random_uuid(), (SELECT id FROM owner_ids LIMIT 1 OFFSET 0), 'Maruti', 'Swift', 'LXi', 2024, 'White', 5, 'petrol'::fueltype, 'manual'::transmissiontype, 19.2, 'Hyderabad', 'Telangana', 'Kondapur, Hyderabad', 299, 1999, 5000, 'TS09AB0001', 'active'::vehiclestatus, 'approved'::kycstatus, jsonb_build_object('Power Steering', true, 'Power Windows', true, 'Air Conditioning', true, 'ABS', true, 'Airbags', true, 'Bluetooth', true, 'USB Charging', true, 'Touchscreen', true, 'Parking Sensors', false, 'Climate Control', false), now(), now()),
  (gen_random_uuid(), (SELECT id FROM owner_ids LIMIT 1 OFFSET 0), 'Maruti', 'Swift', 'VXi', 2023, 'Silver', 5, 'petrol'::fueltype, 'automatic'::transmissiontype, 18.5, 'Hyderabad', 'Telangana', 'Jubilee Hills, Hyderabad', 399, 2499, 7000, 'TS09AB0002', 'active'::vehiclestatus, 'approved'::kycstatus, jsonb_build_object('Power Steering', true, 'Power Windows', true, 'Air Conditioning', true, 'ABS', true, 'Airbags', true, 'Bluetooth', true, 'USB Charging', true, 'Touchscreen', true, 'Parking Sensors', true, 'Climate Control', true), now(), now()),
  (gen_random_uuid(), (SELECT id FROM owner_ids LIMIT 1 OFFSET 1), 'Hyundai', 'i20', 'Sportz', 2024, 'Red', 5, 'petrol'::fueltype, 'manual'::transmissiontype, 20.5, 'Bangalore', 'Karnataka', 'Indiranagar, Bangalore', 349, 2299, 6000, 'KA05AB0003', 'active'::vehiclestatus, 'approved'::kycstatus, jsonb_build_object('Power Steering', true, 'Power Windows', true, 'Air Conditioning', true, 'ABS', true, 'Airbags', true, 'Bluetooth', true, 'USB Charging', true, 'Touchscreen', true, 'Parking Sensors', true, 'Climate Control', true), now(), now()),
  (gen_random_uuid(), (SELECT id FROM owner_ids LIMIT 1 OFFSET 1), 'Tata', 'Nexon', 'XE', 2023, 'Black', 5, 'diesel'::fueltype, 'manual'::transmissiontype, 17.3, 'Bangalore', 'Karnataka', 'Whitefield, Bangalore', 449, 2899, 8000, 'KA05AB0004', 'active'::vehiclestatus, 'approved'::kycstatus, jsonb_build_object('Power Steering', true, 'Power Windows', true, 'Air Conditioning', true, 'ABS', true, 'Airbags', true, 'Bluetooth', true, 'USB Charging', true, 'Touchscreen', true, 'Parking Sensors', true, 'Climate Control', true), now(), now()),
  (gen_random_uuid(), (SELECT id FROM owner_ids LIMIT 1 OFFSET 0), 'Honda', 'City', 'SV', 2024, 'Blue', 5, 'petrol'::fueltype, 'manual'::transmissiontype, 18.2, 'Mumbai', 'Maharashtra', 'Andheri, Mumbai', 399, 2599, 7000, 'MH02AB0005', 'active'::vehiclestatus, 'approved'::kycstatus, jsonb_build_object('Power Steering', true, 'Power Windows', true, 'Air Conditioning', true, 'ABS', true, 'Airbags', true, 'Bluetooth', true, 'USB Charging', true, 'Touchscreen', true, 'Parking Sensors', true, 'Climate Control', true), now(), now()),
  (gen_random_uuid(), (SELECT id FROM owner_ids LIMIT 1 OFFSET 1), 'Hyundai', 'Creta', 'SX', 2023, 'White', 5, 'diesel'::fueltype, 'automatic'::transmissiontype, 15.8, 'Mumbai', 'Maharashtra', 'Bandra, Mumbai', 599, 3999, 10000, 'MH02AB0006', 'active'::vehiclestatus, 'approved'::kycstatus, jsonb_build_object('Power Steering', true, 'Power Windows', true, 'Air Conditioning', true, 'ABS', true, 'Airbags', true, 'Bluetooth', true, 'USB Charging', true, 'Touchscreen', true, 'Parking Sensors', true, 'Climate Control', true), now(), now()),
  (gen_random_uuid(), (SELECT id FROM owner_ids LIMIT 1 OFFSET 0), 'Mahindra', 'XUV500', 'W4', 2022, 'Silver', 5, 'diesel'::fueltype, 'manual'::transmissiontype, 14.5, 'Delhi', 'Delhi', 'Gurgaon, Delhi NCR', 649, 4299, 12000, 'DL01AB0007', 'active'::vehiclestatus, 'approved'::kycstatus, jsonb_build_object('Power Steering', true, 'Power Windows', true, 'Air Conditioning', true, 'ABS', true, 'Airbags', true, 'Bluetooth', true, 'USB Charging', true, 'Touchscreen', true, 'Parking Sensors', true, 'Climate Control', true), now(), now()),
  (gen_random_uuid(), (SELECT id FROM owner_ids LIMIT 1 OFFSET 1), 'Toyota', 'Fortuner', '4x2 MT', 2023, 'Black', 7, 'diesel'::fueltype, 'manual'::transmissiontype, 11.8, 'Delhi', 'Delhi', 'Noida, Delhi NCR', 999, 5999, 15000, 'DL01AB0008', 'active'::vehiclestatus, 'approved'::kycstatus, jsonb_build_object('Power Steering', true, 'Power Windows', true, 'Air Conditioning', true, 'ABS', true, 'Airbags', true, 'Bluetooth', true, 'USB Charging', true, 'Touchscreen', true, 'Parking Sensors', true, 'Climate Control', true), now(), now()),
  (gen_random_uuid(), (SELECT id FROM owner_ids LIMIT 1 OFFSET 0), 'Kia', 'Seltos', 'HT', 2024, 'Red', 5, 'petrol'::fueltype, 'automatic'::transmissiontype, 16.5, 'Chennai', 'Tamil Nadu', 'T. Nagar, Chennai', 549, 3599, 9000, 'TN07AB0009', 'active'::vehiclestatus, 'approved'::kycstatus, jsonb_build_object('Power Steering', true, 'Power Windows', true, 'Air Conditioning', true, 'ABS', true, 'Airbags', true, 'Bluetooth', true, 'USB Charging', true, 'Touchscreen', true, 'Parking Sensors', true, 'Climate Control', true), now(), now()),
  (gen_random_uuid(), (SELECT id FROM owner_ids LIMIT 1 OFFSET 1), 'Maruti', 'Ertiga', 'VXi', 2023, 'Silver', 7, 'petrol'::fueltype, 'manual'::transmissiontype, 16.3, 'Chennai', 'Tamil Nadu', 'Kodambakkam, Chennai', 349, 2299, 6000, 'TN07AB0010', 'active'::vehiclestatus, 'approved'::kycstatus, jsonb_build_object('Power Steering', true, 'Power Windows', true, 'Air Conditioning', true, 'ABS', true, 'Airbags', true, 'Bluetooth', true, 'USB Charging', true, 'Touchscreen', false, 'Parking Sensors', true, 'Climate Control', false), now(), now()),
  (gen_random_uuid(), (SELECT id FROM owner_ids LIMIT 1 OFFSET 0), 'Maruti', 'Baleno', 'Sigma', 2024, 'Orange', 5, 'petrol'::fueltype, 'manual'::transmissiontype, 19.0, 'Pune', 'Maharashtra', 'Baner, Pune', 299, 1999, 5000, 'MH14AB0011', 'active'::vehiclestatus, 'approved'::kycstatus, jsonb_build_object('Power Steering', true, 'Power Windows', true, 'Air Conditioning', true, 'ABS', true, 'Airbags', true, 'Bluetooth', true, 'USB Charging', true, 'Touchscreen', true, 'Parking Sensors', true, 'Climate Control', true), now(), now()),
  (gen_random_uuid(), (SELECT id FROM owner_ids LIMIT 1 OFFSET 1), 'MG', 'Hector', 'Style', 2023, 'Pearl White', 5, 'petrol'::fueltype, 'automatic'::transmissiontype, 12.7, 'Pune', 'Maharashtra', 'Viman Nagar, Pune', 749, 4899, 11000, 'MH14AB0012', 'active'::vehiclestatus, 'approved'::kycstatus, jsonb_build_object('Power Steering', true, 'Power Windows', true, 'Air Conditioning', true, 'ABS', true, 'Airbags', true, 'Bluetooth', true, 'USB Charging', true, 'Touchscreen', true, 'Parking Sensors', true, 'Climate Control', true), now(), now());
